name: Deploy UltimatePOS to Niagahoster

on:
  push:
    branches:
      - main  # Deploy otomatis setiap ada push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Langkah 1: Checkout kode dari GitHub
      - name: Checkout code
        uses: actions/checkout@v3

      # Langkah 2: Upload ke Niagahoster via FTP
      - name: Deploy to Niagahoster
        if: github.ref == 'refs/heads/main'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}     
          port: 21
          server-dir: pos.elangmasmedia.com/
          
         
           
