name: Deploy UltimatePOS to Niagahoster

on:
  push:
    branches:
      - main  # Deploy otomatis setiap ada push ke branch main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Langkah 1: Checkout kode dari GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Langkah 2: Upload ke Niagahoster via FTP
      - name: Deploy to Niagahoster
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./ 
          server-dir: /  # Path root dari akun FTP
          method: ftps
          port: 21
          passive: true
          time-between-retries: 15s
          retry-count: 5
